
// get all customers
GET http://localhost:3000/customers HTTP/1.1

###
// get all orders
GET http://localhost:3000/orders HTTP/1.1

###
// get all specific order
GET http://localhost:3000/orders/9 HTTP/1.1

###

// create customer
POST http://localhost:3000/customers HTTP/1.1
content-type: application/json

{"customerId":18, "customerName": "Ana Peterson"}
###

// create customer
POST http://localhost:3000/customers HTTP/1.1
content-type: application/json

{"customerId":22, "customerName": "Luka Miga"}
###

// create new order
POST http://localhost:3000/customers/17 HTTP/1.1
content-type: application/json

{
            "orderId": 9,
            "customerId": 17,
            "itemId": [
                1,7,4
            ]
        }
###

// get customer by id
GET http://localhost:3000/customers/15 HTTP/1.1

###

// update customer
PUT  http://localhost:3000/customers/15 HTTP/1.1
content-type: application/json

{"customerId":15, "customerName": "John Johnson UPDATED!"}
###

// delete customer
DELETE  http://localhost:3000/customers/15 HTTP/1.1

###